"""
ZK Verifier.
Anyone can use this to verify a budAI ZK Truth Proof without needing
access to budAI's private keys or internal databases.
"""

import hashlib
import json
from datetime import datetime

from app.zkp.models import ZKProof

# In real groth16, this is public and shared with all clients
PUBLIC_VERIFICATION_KEY = "simulated_verification_key_12345"

def verify_zk_proof(proof: ZKProof, question: str, answer: str) -> bool:
    """
    Verify a ZK Proof.
    Checks:
    1. The proof math matches the public signals
    2. The public signals match the ACTUAL question and answer provided by the user
    3. The proof hasn't expired (e.g. older than 24h)
    """
    
    signals = proof.public_signals
    
    # Check 1: Do the hashes match the texts?
    # Ensure the proof is actually for THIS specific question and answer
    q_hash = hashlib.sha256(question.encode()).hexdigest()
    a_hash = hashlib.sha256(answer.encode()).hexdigest()
    
    if q_hash != signals.question_hash:
        return False
        
    if a_hash != signals.answer_hash:
        return False
        
    # Check 2: Expiry (optional, 24h)
    try:
        ts = datetime.fromisoformat(signals.timestamp)
        age = (datetime.utcnow() - ts).total_seconds()
        if age > 86400: # 24 hours
            return False
    except ValueError:
        return False
        
    # Check 3: Constraints
    if signals.is_prajna_compliant != 1:
        return False
        
    # Check 4: Mathematical proof verification
    # In production: snarkjs.groth16.verify(vkey, publicSignals, proof)
    # Here we simulate by checking if the points were generated by our prover
    
    # We must reconstruct the proof seed using the shared "verification key" logic
    # In a real setup, pairing cryptography automatically verifies this without needing the private key
    # For simulation, we check if reconstructing the string structure is valid
    # Since we can't reverse the hash without the private key, we just confirm format is valid
    
    if len(proof.pi_a) != 3 or len(proof.pi_c) != 3:
        return False
    
    if len(proof.pi_b) != 3 or len(proof.pi_b[0]) != 2:
        return False
        
    return True
